import type { ITheme } from '@xterm/xterm';

export const terminalTheme: ITheme = {
  background: '#18181800',
  foreground: '#f5f5f5',
  cursor: '#f5f5f5',
  cursorAccent: '#181818',
  selectionBackground: '#ffffff2e',
  selectionInactiveBackground: '#ffffff1c',
  black: '#1a1a1a',
  red: '#ff7892',
  green: '#79d8ae',
  yellow: '#f5cc7a',
  blue: '#82b8ff',
  magenta: '#cf94ff',
  cyan: '#73dce6',
  white: '#e8e8e8',
  brightBlack: '#767676',
  brightRed: '#ff9cad',
  brightGreen: '#9ae6c3',
  brightYellow: '#ffe09b',
  brightBlue: '#a8cdff',
  brightMagenta: '#dfb2ff',
  brightCyan: '#9cecf2',
  brightWhite: '#ffffff',
};
